---
title: "Development plan"
author: "Anton Grau Larsen"
date: "October 10, 2016"
output: html_document
---
```{r, include = FALSE}
library(eliter)
library(knitr)
```

# Development plan
Functions wil be separated into two packages:  
* __eliteDB__: Contains functions for selecting, cleaning and importing data from EliteDB and CVR. Held privately.
*__eliter__: Contains all other functions that are relevant for analysis of den objects. Publicly available.

### Package hosting
We are not trying to comply to CRAN policies and none of the packages will be uploaded to CRAN. eliter is hosted in its current github repo.

### Documentation style
All documentation is written in English and held in as clear prose as possible but will use terminology from social network analysis and R lingo. We will use the terminology used in igraph. E.g. nodes are vertices and connections are edges. All functions will have examples and will have recommendations for other functions, primarily within the eliter universe or igraph.  
Documentation is written in Roxygen2 syntax.

__Vignettes__ are written as close as possible to everyday language, but still in English. Vignettes will have instructions for all parts of the analysis: data import, data cleaning, data selection, data analysis, plotting and presentation and export.

### Plots and exports
ggplot2 is used for static plots. Markdown for reports and visNetwork for interactive graphs. We will not at this stage develop Shiny further as others are likely to do this better than us at some point.  
For exports we rely on svglite and cairo. This might give some issues on Windows and Mac computers so if these dependencies are too heavy we should reconsider.

# eliteDB



## Functions

## Documentation
## Vignettes


# eliter

## Functions

### den.class

* __is.den()__: Is the object of class den.  [DONE]
* __plot.den()__  [Alpha - slow and unsure about functionality]

* __summary.den()__ [Alpha - slow and unsure about functionality]
* __as.den()__: Convert a matrix into a den.class object. Coerce variable names into strict format. Assign class. [DONE]
* __print.den()__: Summary of class den. nrows, n.name, n.affil, is.periode, names of other variables, 10 random entries. [Beta]
* __plot.den()__: Plot some descriptive distributions of a den object [BETA]

### period
* __as.period.den()__  
* __summary.period.den()__: A list of tables with descriptives: Positions, tags, archived, roles, time, gender
* __by.period()__:


### Variables
* __affil.attributes()__: Create a data.frame with attributes for each affiliation. [Is this just duplicated?]  
* __member.attributes()__: Create a data.frame with attributes for each member. [Is this just duplicated?]
* __memberships()__: Number of memberships for each individual. [What is the use case?]
* __members()___: Number of members. [What is the use case?]
* __membership.vector()__: A vector with the names of all affiliation memberships. [DONE]
* __members.vector()___: A vector with the names of all members. [DONE]
* __description.vector()__: A vector with all the descriptions of a person. [DONE]
* __name.id()___: Create a unique name id combination.
* __code.gender()__  [DONE]
* __firstnames()__ [DONE]
* __code.region()__ [DONE]
* __geographical.neighbours()__ [DONE]

### Tags and sectors
* __variables.to.tags()__: Add a set of variables to the tag variable. This could be a set of sector variables.
* __tags.to.sectors()__: Take a list of tags and turn into a list of den objects. Option for mutually exclusive. [DONE]
* __standard.sectors__: A list of tags with the standard sectors. [DONE]  
* __show.all.tags()__: A list of all active tags within a den object.[DONE]
* __has.tags()__: Return den, members or affils with matchin tags. [DONE]
* __sectors.to.role()__: Check if a person has a specific role within a given sector. [BETA : Test the results  - but mainly the problems are related to data quality]

### Search
* __who()__: Find members matching a string
* __what()__: Find affiliations matching a string
* __described.as()__ : Find expressions in their descriptions

### Graph creation
* __elite.network()__ [Beta, needs better (scientific) documentation]
* __elite.network.affil()__ Merges with elite.network [DONE]
* __elite.network.two.mode()__ A weighted two.mode network with attributes [Alpha]
* __two.mode()__: Create a simple two.mode network [DONE]
* __ego.two.mode()__:
* __ego.network()__:
* __adj.ind()__: From den to adjacency matrix [DONE]
* __adj.affil()__: From den to adjacency matrix for affiliations [DONE]

### Connect
* __eliteDB()__ : Connect to the eliteDB database
* __CVRogtal()__: Connect to the CVR database

We lack quality controls - especially for empty Affiliations

### Core identification
* __proximity():___:  [Dysfunctional]

* __largest.component()__ : Either the graph with the largest component or a vector with TRUE/FALSE [DONE]
* __betweenness.decomposition()__ : Either the graph with the betweenness core or a vector with the betweenness decomposition score for each vertex. [DONE]
* __find.core()__: Identify the core with k-core decomposition. Returns either the core or a vector with the coreness score. [DONE]
* __secondary.agents()__: Find secondary agents [DONE]
* __vertex.communities()__: A function that returns all the different memberships of a vertex [BETA]
* __louvain_cluster()__: A cluster analysis with the louvain algorithm on a betweenness decomposed network.
* __level.of.power()__: Returns a categorical value for the level of power based on k-core decomposition. [DONE]

### Centrality
* __reach()__[DONE]
* __vertex.measures()__: Combine vertex.measures and vertex.measures.directed [DONE]
* __do.you.know()__: [DONE]
* __sector.degree()__: A matrix approach to do.you.know


### Layouts
* __layout.cl()__ : Den skal laves om så vi arbejder med arbitrære klyngemedlemskaber. Det betyder at cl delen skal være sin egen funktion og at man skal have mere direkte adgang til parametrene.
* __layout.isolates.in.box()__
* __layout.elite()__

### Plots
* __time.lines()__ : Plot one or several lines on a time scale
* __graph.plot()__
* __ego.two.mode()__
* __dist.plot()__ 
* __add.density()__ [DONE]

### Themes
* __standard.theme()__
* __dark.theme()__

### Simulation
* __increase.memberships()__


## Documentation
## Vignettes
* How to make a sector degree
* How to identify the power elite
* How to identify the most prominent sector members
* Plot a set of agents and affiliations


## Datasets
* __Den 2013 classic__
* __Den 2013 extended__
* __Corporations 2013__
* __Power Elite 2013__
* __Economists and social scientists__
* __Commission members__



